import { programBatch, questionBatch } from '../../authoring/expansion';

export const challenges = [
  ...programBatch('stage-cpp1', 'cpp', [
    [1, 'A reference aliases its initializer', 'references', 'easy', 'int score = 4;\nint& alias = score;\nalias += 3;\nstd::cout << score;', ['7', '4', '3', '0'], 'alias is another name for score, so updating the reference updates the original object.', 'A reference is not a separate copied integer.'],
    [2, 'Copying an int is independent', 'values', 'easy', 'int original = 8;\nint copy = original;\ncopy = 2;\nstd::cout << original << " " << copy;', ['8 2', '2 2', '8 8', '2 8'], 'The copy has its own integer storage. Reassigning it does not change the original object.', 'Look for a reference marker in the declaration.'],
    [3, 'Auto without a reference copies', 'auto', 'medium', 'int original = 5;\nauto copy = original;\ncopy++;\nstd::cout << original;', ['5', '6', '0', 'Compilation fails'], 'Plain auto deduces int here, not int&, so copy is an independent value.', 'Type deduction does not automatically create aliases.'],
    [4, 'Auto reference retains aliasing', 'auto', 'medium', 'int original = 5;\nauto& alias = original;\nalias++;\nstd::cout << original;', ['6', '5', '1', 'Compilation fails'], 'The explicit reference declarator makes alias refer to original even though the base type is deduced.', 'The ampersand changes the declaration contract.'],
    [5, 'String appending is explicit mutation', 'strings', 'easy', 'std::string word = "code";\nword += "r";\nstd::cout << word;', ['coder', 'code', 'r', 'code r'], 'operator+= appends the supplied characters to the existing string object.', 'Appending does not automatically insert a separator.'],
    [6, 'Substring length rather than end index', 'strings', 'medium', 'std::string word = "planet";\nstd::cout << word.substr(1, 3);', ['lan', 'la', 'lane', 'pla'], 'The second substr argument is a character count, not an exclusive end index. Starting at 1, three characters form lan.', 'Check the API meaning of the second argument.'],
    [7, 'A string copy owns its value', 'strings', 'easy', 'std::string original = "cat";\nstd::string copy = original;\ncopy[0] = \'b\';\nstd::cout << original << " " << copy;', ['cat bat', 'bat bat', 'cat cat', 'bat cat'], 'The two strings have independent value semantics. Modifying a character in copy does not alter original.', 'Copying a standard string is not reference assignment.'],
    [8, 'Finding a missing substring', 'strings', 'medium', 'std::string word = "alpha";\nstd::cout << std::boolalpha\n          << (word.find("z") == std::string::npos);', ['true', 'false', '0', '5'], 'find reports a failed search with npos. Comparing to that sentinel avoids assuming a particular numeric representation.', 'Use the named sentinel rather than a platform-sized integer.'],
    [9, 'Vector push changes size', 'vectors', 'easy', 'std::vector<int> values{1, 2};\nvalues.push_back(3);\nstd::cout << values.size();', ['3', '2', '6', '1'], 'push_back adds one element at the end, increasing size from two to three.', 'Count logical elements, not capacity.'],
    [10, 'Reserve does not create elements', 'vectors', 'medium', 'std::vector<int> values{1, 2};\nvalues.reserve(20);\nstd::cout << values.size();', ['2', '20', '0', '22'], 'reserve changes available capacity if necessary but leaves the number of constructed elements unchanged.', 'Reserved storage and logical size are separate.'],
    [11, 'Resize constructs new integers', 'vectors', 'medium', 'std::vector<int> values{4};\nvalues.resize(3);\nstd::cout << values[1] << " " << values[2];', ['0 0', '4 4', '3 3', '1 2'], 'New int elements created by this resize overload are value-initialized to zero.', 'This operation changes size, unlike reserve.'],
    [12, 'Range-for by value', 'loops', 'medium', 'std::vector<int> values{2, 4};\nfor (auto value : values) value *= 2;\nstd::cout << values[0] << " " << values[1];', ['2 4', '4 8', '4 4', '2 8'], 'Each iteration variable is a value copy. Changing it does not assign back into the vector.', 'Check whether the loop variable is a reference.'],
    [13, 'Range-for by reference', 'loops', 'medium', 'std::vector<int> values{2, 4};\nfor (auto& value : values) value *= 2;\nstd::cout << values[0] << " " << values[1];', ['4 8', '2 4', '4 4', '2 8'], 'The reference loop variable aliases each vector element, so multiplication updates the elements in place.', 'The ampersand makes each iteration operate on stored elements.'],
    [14, 'Sorting a vector in place', 'algorithms', 'easy', 'std::vector<int> values{5, 1, 3};\nstd::sort(values.begin(), values.end());\nstd::cout << values.front() << " " << values.back();', ['1 5', '5 3', '3 1', '1 3'], 'std::sort reorders the vector range ascending with the default comparison, putting the minimum first and maximum last.', 'The algorithm mutates the iterator range.'],
    [15, 'Accumulate starts from the supplied initial value', 'algorithms', 'medium', 'std::vector<int> values{2, 3};\nstd::cout << std::accumulate(values.begin(), values.end(), 10);', ['15', '5', '10', '23'], 'accumulate begins at 10 and adds both vector values, yielding 15.', 'Do not omit the initial accumulator.'],
    [16, 'Set insertion deduplicates', 'containers', 'easy', 'std::set<int> values{3, 1, 3};\nvalues.insert(1);\nstd::cout << values.size();', ['2', '3', '4', '1'], 'std::set holds unique keys under its comparison, so repeated 1 and 3 values do not add entries.', 'Count distinct keys after both initialization and insertion.'],
    [17, 'Map subscript inserts a missing integer', 'containers', 'medium', 'std::map<std::string, int> counts;\nconst int value = counts["new"];\nstd::cout << value << " " << counts.size();', ['0 1', '0 0', '1 1', 'Compilation fails'], 'operator[] inserts a missing key with a value-initialized int value of zero, so the map gains one entry before size is queried.', 'A lookup syntax can also mutate this container.'],
    [18, 'A lambda captures a snapshot', 'lambdas', 'hard', 'int value = 3;\nauto read = [value]() { return value; };\nvalue = 8;\nstd::cout << read();', ['3', '8', '0', 'Compilation fails'], 'An explicit by-value capture stores a copy at lambda creation. Later changes to the original do not alter the captured value.', 'Identify when and how the capture is made.'],
    [19, 'A lambda captures a reference', 'lambdas', 'hard', 'int value = 3;\nauto read = [&value]() { return value; };\nvalue = 8;\nstd::cout << read();', ['8', '3', '0', 'Compilation fails'], 'The lambda refers to the still-live original variable, so reading it after reassignment observes 8.', 'The reference is valid here because the original is still alive.'],
    [20, 'A class constructor initializes a member', 'classes', 'medium', 'struct Counter {\n  int value;\n  explicit Counter(int start) : value(start) {}\n  void increment() { ++value; }\n};\nCounter counter(6);\ncounter.increment();\nstd::cout << counter.value;', ['7', '6', '1', '0'], 'The member initializer sets value to 6 before the constructor body. increment then adds one.', 'Construction happens before the member function call.']
  ]),
  ...questionBatch('stage-cpp1', 'b', 'cpp', 'cpp-fundamentals', 'quiz', [
    [21, 'Reference initialization', 'references', 'easy', 'For an ordinary local lvalue reference declaration int& ref, what must be supplied?', ['An initializer binding it to a suitable object', 'A later assignment sometime before program exit', 'A null pointer as the default reference target', 'A mandatory heap allocation'], 'A local reference must be bound at initialization; it cannot sit unbound waiting for a later assignment.', 'A reference needs its referent when it is declared.'],
    [22, 'Reference assignment does not rebind', 'references', 'medium', 'int& ref is already bound to first. What does ref = second do?', ['Assigns the value of second into first', 'Rebinds ref to second permanently', 'Makes first and second one storage allocation', 'Deletes first and constructs a new reference'], 'Ordinary assignment through a reference changes the referred object. The reference itself remains bound to its original object.', 'Separate changing an object from changing an alias target.'],
    [23, 'Const reference parameter', 'functions', 'easy', 'Why pass a large std::string as const std::string& when only reading it during the call?', ['Avoid a parameter copy while preventing mutation through that reference', 'Guarantee the caller string is moved from', 'Require a heap allocation for every character', 'Let the function resize the caller string despite const'], 'A const reference can observe the existing object without a by-value copy and disallows non-const access through that parameter.', 'The interface can express read-only borrowed access.'],
    [24, 'Returning a local reference', 'lifetime', 'medium', 'Why is returning a reference to an ordinary local std::string unsafe?', ['The referred object is destroyed when the function exits', 'References can never be returned by any function', 'Every returned reference automatically makes a deep copy', 'The local object is guaranteed to become static'], 'The reference would outlive the local object. Returning a value or a reference to appropriately longer-lived storage avoids that dangling reference.', 'A reference does not extend every object lifetime.'],
    [25, 'RAII resource release', 'raii', 'medium', 'What is the central RAII idea?', ['Tie resource ownership and release to object lifetime', 'Release every resource only when the operating system shuts down', 'Use raw pointers for every resource without ownership rules', 'Disable destructors whenever an exception occurs'], 'A resource-owning object acquires a resource and releases it through destruction, supporting predictable cleanup across normal scope exit and unwinding.', 'Use language-managed lifetime to manage a non-language resource.'],
    [26, 'Unique ownership pointer', 'ownership', 'medium', 'What ownership does std::unique_ptr express?', ['Exclusive ownership transferable by move', 'Unlimited copying of the same ownership record', 'A non-owning view that never deletes its object', 'Automatic sharing across processes over a network'], 'unique_ptr has one owner at a time and is movable rather than copyable, helping avoid ambiguous deletion responsibility.', 'Unique refers to ownership, not merely the pointed value.'],
    [27, 'Shared ownership cycle', 'ownership', 'hard', 'Two objects own each other through shared_ptr and no external owner remains. What can happen?', ['Their reference counts can keep both objects alive', 'The cycle is always collected immediately by the language', 'Both pointers automatically become weak_ptr', 'The program is guaranteed to fail compilation'], 'Reference counting alone cannot reclaim a strong ownership cycle. A weak or non-owning link may be needed in the design.', 'Each object can keep the other reference count above zero.'],
    [28, 'Move is a cast, not an operation by itself', 'move-semantics', 'hard', 'What does std::move(expression) itself do?', ['Casts the expression to permit move-aware overload selection', 'Always transfers heap memory immediately', 'Always deletes the original object', 'Always sets the original value to zero'], 'std::move enables a move operation to be selected; the receiving constructor or assignment performs any actual transfer.', 'The cast and the operation consuming its result are different.'],
    [29, 'Moved-from string assumptions', 'move-semantics', 'hard', 'After moving from a std::string using a standard move operation, what should portable code assume about its value?', ['It is valid but its value is generally unspecified', 'It is always the exact original text', 'It is always a dangling object that cannot be destroyed', 'It is guaranteed to contain the word moved'], 'A moved-from standard-library object can still be destroyed or reassigned, but code should not assume a specific string content.', 'Valid lifetime does not imply a prescribed value.'],
    [30, 'Vector reallocation invalidates references', 'vectors', 'hard', 'What can happen to references and iterators into a vector when push_back reallocates its storage?', ['They are invalidated', 'They always follow the elements to their new addresses', 'They become linked-list iterators automatically', 'Only references to integers are invalidated'], 'Reallocation relocates vector elements to new storage. Existing pointers, references and iterators no longer designate the relocated elements.', 'An old address does not track a moved storage allocation.'],
    [31, 'Bounds-checked vector access', 'vectors', 'easy', 'Which std::vector member performs bounds checking and throws std::out_of_range on an invalid index?', ['at', 'operator[]', 'data', 'capacity'], 'at checks its index. operator[] requires a valid index rather than promising this exception behavior.', 'Choose the accessor with a checked contract.'],
    [32, 'End iterator is a boundary', 'iterators', 'medium', 'What does container.end() represent?', ['A past-the-end iterator, not an element to dereference', 'The last element value itself', 'The number of allocated bytes', 'An iterator always equal to begin even for nonempty containers'], 'The half-open iterator range includes begin and excludes end, allowing empty ranges to have equal boundaries.', 'A range boundary need not identify a stored element.'],
    [33, 'Erase returns a continuation iterator', 'iterators', 'medium', 'When erasing through a vector iterator in a loop, what helps continue safely?', ['Use the iterator returned by erase', 'Keep incrementing the invalidated erased iterator', 'Assume erase preserves every iterator unconditionally', 'Compare the erased element address to nullptr only'], 'erase returns an iterator to the element following the removed range, while affected old iterators can be invalidated.', 'Use the API-provided continuation point.'],
    [34, 'Default access of class versus struct', 'classes', 'easy', 'Without an explicit access label, how do members of class and struct differ?', ['class members are private; struct members are public', 'Both are always public', 'Both are always private', 'class members are public; struct members are private'], 'The default member access differs, though both constructs otherwise support methods, constructors and access labels.', 'The difference is a default, not a ban on methods.'],
    [35, 'Const-qualified member function', 'classes', 'medium', 'What does a trailing const on a normal member function principally promise?', ['It does not modify non-mutable members through this', 'It returns only a compile-time constant', 'It can never read object members', 'It makes every object of the class immutable forever'], 'The implicit object parameter is const-qualified. Mutable members and external side effects have separate rules.', 'The qualifier constrains access through the current object.'],
    [36, 'Override catches signature mistakes', 'inheritance', 'medium', 'Why annotate an intended virtual override with override?', ['The compiler checks that it really overrides a base virtual function', 'It automatically makes every base member public', 'It prevents the method from ever being called', 'It converts the class into a namespace'], 'override turns accidental signature mismatches into compile errors instead of silently introducing a different function.', 'Express the intended relationship for the compiler to verify.'],
    [37, 'Polymorphic deletion', 'inheritance', 'hard', 'A derived object is deleted through a base pointer. What should the base have to support this polymorphic destruction correctly?', ['A suitable virtual destructor', 'A public integer named type', 'A nonvirtual print method only', 'An empty constructor with no destructor'], 'A virtual destructor ensures destruction dispatch reaches the derived object when deleting through a base pointer.', 'Construction and destruction dispatch are part of the ownership contract.'],
    [38, 'Catch exceptions without slicing', 'exceptions', 'medium', 'Why commonly catch standard exceptions as const std::exception&?', ['It avoids copying and preserves polymorphic exception information', 'It forces all exceptions to be converted to integers', 'It prevents the handler from calling what()', 'It guarantees the exception was never thrown'], 'Catching by reference avoids value slicing, while const allows observation without modifying the exception object.', 'A base-class value copy can lose derived information.'],
    [39, 'nullptr has a pointer-oriented type', 'pointers', 'easy', 'Why prefer nullptr to an integer zero literal when expressing a null pointer in modern C++?', ['It distinguishes null-pointer intent from an int argument', 'It always points to a newly allocated object', 'It makes all pointer dereferences safe', 'It automatically checks every array bound'], 'nullptr has its own null-pointer type, distinguishing pointer intent from an int argument in overload resolution.', 'The literal type matters before conversions are chosen.'],
    [40, 'Use standard value-owning members', 'classes', 'medium', 'Why can a class made only of ordinary std::string and std::vector members often avoid custom copy/destructor code?', ['Those members already manage their own resource lifetimes', 'Such classes can never be copied at all', 'Their memory is never released by any mechanism', 'The compiler converts every member into a global variable'], 'Composing resource-managing value types often lets generated special members do the right thing, reducing manual ownership mistakes.', 'Ownership behavior can be delegated to well-defined member types.']
  ])
];
