import { programBatch, questionBatch } from '../../authoring/expansion';

export const challenges = [
  ...programBatch('stage-c1', 'c', [
    [1, 'Integer division truncates', 'arithmetic', 'easy', 'printf("%d", 17 / 5);', ['3', '3.4', '4', '2'], 'Both operands are integers, so the division result discards the fractional part toward zero.', 'Check operand types before dividing.'],
    [2, 'Negative division is toward zero', 'arithmetic', 'medium', 'printf("%d", -17 / 5);', ['-3', '-4', '3', '-3.4'], 'In C11, integer division truncates toward zero; a negative quotient is not rounded down toward negative infinity.', 'Truncation and mathematical floor differ for negative values.'],
    [3, 'Promote before division', 'conversions', 'easy', 'printf("%.1f", 7 / 2.0);', ['3.5', '3.0', '4.0', '2.5'], 'The floating operand causes floating-point division. The format prints one digit after the decimal point.', 'One floating operand changes the arithmetic conversion.'],
    [4, 'An array initializer fills the rest', 'arrays', 'easy', 'int values[4] = {8, 2};\nprintf("%d", values[3]);', ['0', '2', '8', '4'], 'Remaining elements of this partially initialized array are initialized to zero, unlike an entirely uninitialized automatic array.', 'This array has an initializer.'],
    [5, 'Character array includes a terminator', 'strings', 'medium', 'char word[] = "code";\nprintf("%zu", sizeof word);', ['5', '4', '8', '1'], 'The inferred array contains four characters plus the terminating null character. sizeof measures the whole array here.', 'Count the terminator as stored data.'],
    [6, 'String length excludes the terminator', 'strings', 'easy', 'char word[] = "code";\nprintf("%zu", strlen(word));', ['4', '5', '3', '0'], 'strlen counts characters before the first null terminator, not the storage size including that terminator.', 'Length and allocated size are different quantities.'],
    [7, 'Pointer dereference updates the object', 'pointers', 'easy', 'int value = 4;\nint *pointer = &value;\n*pointer = 9;\nprintf("%d", value);', ['9', '4', '0', '1'], 'pointer holds the address of value. Assigning through *pointer writes to that same integer object.', 'Follow the address to the object it designates.'],
    [8, 'Pointer arithmetic follows element size', 'pointers', 'medium', 'int values[] = {6, 8, 10};\nint *pointer = values;\nprintf("%d", *(pointer + 2));', ['10', '8', '6', '2'], 'Adding two to an int pointer advances by two int elements, reaching the third array element.', 'Pointer increments count elements rather than raw bytes.'],
    [9, 'Const pointer target can be observed', 'pointers', 'medium', 'int value = 7;\nconst int *pointer = &value;\nvalue = 12;\nprintf("%d", *pointer);', ['12', '7', '0', 'Compilation fails'], 'The pointer prohibits modification through that access path, but the original non-const object can still be changed through value.', 'Read-only access through one pointer does not freeze every alias.'],
    [10, 'Logical operators produce int truth values', 'operators', 'easy', 'printf("%d", 4 && 9);', ['1', '9', '4', '0'], 'Logical AND in C returns int 1 when both operands compare unequal to zero, not one of the original operands.', 'Do not import JavaScript operand-return behavior into C.'],
    [11, 'Short-circuit avoids the increment', 'operators', 'medium', 'int count = 0;\nint result = 0 && ++count;\nprintf("%d %d", result, count);', ['0 0', '0 1', '1 1', '1 0'], 'A false left operand determines logical AND, so the right operand is not evaluated and count is unchanged.', 'Is evaluation of the right operand necessary?'],
    [12, 'Bitwise mask', 'bitwise', 'medium', 'unsigned int flags = 13u;\nprintf("%u", flags & 3u);', ['1', '3', '13', '15'], '13 is binary 1101 and 3 is 0011; bitwise AND retains only the shared low bit.', 'Align the binary digits and compare each position.'],
    [13, 'Switch falls through until break', 'control-flow', 'medium', 'int total = 0;\nswitch (1) {\n  case 1: total += 2;\n  case 2: total += 3; break;\n  default: total += 9;\n}\nprintf("%d", total);', ['5', '2', '3', '14'], 'Case labels do not stop execution. After entering case 1, the code continues through case 2 until break.', 'Find the first executed break.'],
    [14, 'Continue skips an addition', 'loops', 'easy', 'int total = 0;\nfor (int value = 1; value <= 4; value++) {\n  if (value == 2) continue;\n  total += value;\n}\nprintf("%d", total);', ['8', '10', '1', '6'], 'The loop adds 1, 3 and 4; continue skips only the iteration whose value is 2.', 'List the values that reach the addition.'],
    [15, 'An inner declaration shadows', 'scope', 'medium', 'int number = 3;\n{\n  int number = 8;\n  number++;\n}\nprintf("%d", number);', ['3', '8', '9', '4'], 'The block declares a separate automatic variable. Incrementing it does not change the outer number.', 'Match each use to the nearest in-scope declaration.'],
    [16, 'Designated initializer positions', 'arrays', 'medium', 'int values[5] = {[2] = 7};\nprintf("%d %d", values[1], values[2]);', ['0 7', '7 0', '7 7', '0 0'], 'The designated initializer sets element 2, while unspecified elements in the initialized array are zero-initialized.', 'The bracket gives an index, not an element count.'],
    [17, 'Copying a structure value', 'structs', 'medium', 'struct Point { int column; int row; };\nstruct Point original = {2, 3};\nstruct Point copy = original;\ncopy.column = 9;\nprintf("%d %d", original.column, copy.column);', ['2 9', '9 9', '2 2', '9 2'], 'Structure assignment copies member values. These integer members are independent in the two structure objects.', 'A structure value copy is not another name for the same structure.'],
    [18, 'Comma operator result', 'operators', 'hard', 'int value = 1;\nint result = (value += 2, value * 3);\nprintf("%d %d", value, result);', ['3 9', '1 3', '3 3', '9 9'], 'The comma operator sequences the left expression before the right and yields the right result. value becomes 3, then result becomes 9.', 'These comma-separated expressions are sequenced by the operator.'],
    [19, 'Sizeof a non-VLA expression does not increment', 'sizeof', 'hard', 'int count = 4;\nsize_t bytes = sizeof(count++);\n(void)bytes;\nprintf("%d", count);', ['4', '5', '0', '1'], 'For this non-variable-length operand, sizeof does not evaluate count++, so its side effect does not occur.', 'The operand is an ordinary int expression, not a variable-length array.'],
    [20, 'First null ends a C string', 'strings', 'medium', 'char text[] = {\'a\', \'b\', \'\\0\', \'c\', \'\\0\'};\nprintf("%zu", strlen(text));', ['2', '3', '4', '5'], 'strlen stops at the first null character. Later stored characters do not belong to the string measured from text.', 'Find the first terminator rather than the end of the array.']
  ]),
  ...questionBatch('stage-c1', 'b', 'c', 'c-fundamentals', 'quiz', [
    [21, 'Portable size of an int', 'types', 'medium', 'Which assumption about sizeof(int) is portable C?', ['Its size is implementation-defined within standard constraints', 'It must equal 4 on every conforming implementation', 'It must equal sizeof(char) on every implementation', 'It must always equal 8'], 'C specifies minimum representable ranges and ordering constraints, not one universal byte size for int.', 'Do not generalize a familiar machine layout to all implementations.'],
    [22, 'A C byte has a defined size unit', 'sizeof', 'easy', 'What is sizeof(char) required to be?', ['1', '8', '4', 'Platform-dependent with no restriction'], 'sizeof measures C bytes, and char occupies exactly one such byte. The number of bits in that byte is a separate property.', 'Distinguish a size unit from its bit count.'],
    [23, 'Signed overflow is not wrapping arithmetic', 'arithmetic', 'hard', 'What does portable C guarantee when a signed int addition exceeds the representable range?', ['No defined result; signed overflow is undefined behavior', 'Guaranteed two-complement wraparound in every implementation', 'Guaranteed saturation at INT_MAX', 'A mandatory catchable runtime exception'], 'Signed arithmetic overflow is undefined behavior in C. Portable code must prevent it or use suitable checked/arbitrary-range arithmetic.', 'Hardware behavior is not necessarily the language guarantee.'],
    [24, 'Unsigned arithmetic wraps by its range', 'arithmetic', 'medium', 'How is unsigned integer arithmetic overflow defined in C?', ['Reduction modulo one more than the maximum representable value', 'Undefined behavior for every unsigned addition', 'Automatic conversion to an arbitrarily large integer', 'A mandatory program termination'], 'Unsigned arithmetic is reduced modulo the range size of that unsigned type, unlike signed overflow.', 'Signed and unsigned overflow have different rules.'],
    [25, 'Uninitialized automatic integer', 'initialization', 'medium', 'What should portable code do before reading an ordinary uninitialized automatic int?', ['Initialize it to a valid value', 'Assume it contains zero', 'Assume it contains the previous function result', 'Print it to discover its guaranteed default'], 'An automatic scalar without initialization has an indeterminate value and must not be treated as a defined default.', 'Initialization rules differ by storage duration.'],
    [26, 'Static storage initialization', 'initialization', 'easy', 'A file-scope int has no explicit initializer. How is it initialized?', ['To zero', 'To a random guaranteed positive number', 'To the address of main', 'It cannot compile without an initializer'], 'Objects with static storage duration are zero-initialized when no explicit initializer is supplied.', 'File scope gives this object static storage duration.'],
    [27, 'Array argument loses bound information', 'arrays', 'hard', 'In void inspect(int values[]), what is the adjusted parameter type?', ['A pointer to int', 'An array carrying its runtime length automatically', 'A complete copy of the caller array', 'A reference type identical to C++ references'], 'An array parameter declaration is adjusted to a pointer parameter. The function needs a separate length contract if it requires bounds.', 'Function parameter syntax has a special adjustment rule.'],
    [28, 'One-past pointer limitation', 'pointers', 'hard', 'A pointer is formed one past the last element of an array. Which use is not permitted?', ['Dereferencing it to read an element', 'Using it as an end marker for traversal', 'Comparing it to a pointer in the same array', 'Subtracting a same-array pointer when the difference fits ptrdiff_t'], 'The one-past position supports traversal boundaries but does not designate an actual array element to access.', 'A valid boundary pointer is not a valid element pointer.'],
    [29, 'Local object lifetime', 'lifetime', 'medium', 'Why is returning a pointer to an ordinary local array unsafe after the function returns?', ['The array lifetime ends when its block execution ends', 'Every returned pointer is forbidden by C', 'Local arrays are always automatically copied to the heap', 'The compiler must make the array permanent'], 'The pointer can outlive the object it designated. Later dereference does not access a live local array.', 'Track the object lifetime separately from the pointer value.'],
    [30, 'Check allocation failure', 'memory', 'easy', 'What should code check before dereferencing a malloc result?', ['Whether the returned pointer is NULL', 'Whether the pointer decimal text is even', 'Whether every byte is already initialized to 1', 'Whether the allocation automatically opened a file'], 'malloc can fail and return a null pointer. Successful allocated storage also needs appropriate initialization before reading.', 'Allocation is an operation that can fail.'],
    [31, 'Release ownership once', 'memory', 'medium', 'For a successfully allocated block that has not been resized, how many times should that allocation be freed?', ['Exactly once when no longer needed', 'Twice to ensure every byte is released', 'Once per pointer alias to the same block', 'Never, because malloc storage always has block scope'], 'Allocation ownership is per block, not per alias. Double-free is undefined behavior, while never freeing long-lived unused blocks leaks resources.', 'Multiple aliases do not create multiple allocations.'],
    [32, 'Realloc failure preservation', 'memory', 'hard', 'For a nonzero requested size, realloc fails and returns NULL. What happens to the original allocation?', ['It remains allocated and valid', 'It is always freed before failure is reported', 'It always doubles in size anyway', 'Its address becomes a valid file handle'], 'On such failure realloc leaves the original object unchanged. Assigning directly over the only pointer can lose access to it.', 'Keep the original pointer until success is established.'],
    [33, 'Freeing null', 'memory', 'easy', 'What is the effect of free(NULL)?', ['No action is performed', 'A required segmentation fault', 'All allocations in the process are freed', 'The current stack frame is destroyed'], 'The standard explicitly allows a null pointer argument to free, which has no effect.', 'The API defines this edge case.'],
    [34, 'String literal modification', 'strings', 'medium', 'Why should a program not write through a char pointer into a string literal?', ['Attempting to modify a string literal is undefined behavior', 'Every string literal has zero length', 'String literals are automatically heap allocations owned by the caller', 'The write is guaranteed to clone the string first'], 'A writable character array initialized from a literal is different from the literal object itself.', 'Distinguish a copied array from a pointer to literal storage.'],
    [35, 'Formatted input needs an address', 'input-output', 'easy', 'For an int age, why does scanf("%d", &age) pass &age?', ['scanf needs a location where it can store the parsed value', 'scanf requires the current age value as a format string', 'The address converts decimal text into hexadecimal', 'Every function argument must always use address-of'], 'scanf writes through the supplied pointer; passing only the integer value would not provide a valid destination.', 'This function produces a result through an output argument.'],
    [36, 'Check scanf conversion count', 'input-output', 'medium', 'What does scanf return on a normal parse attempt?', ['The number of assignments, or EOF on early input failure', 'Always the numeric value just read', 'Always the number of characters in the format string', 'The address of the final input character'], 'The return value lets callers check whether required conversions succeeded before using destination values.', 'Input can fail without assigning every destination.'],
    [37, 'Value parameters and caller mutation', 'functions', 'easy', 'A function receives an int value and reassigns that parameter. Does this alone change the caller int variable?', ['No, the parameter holds a passed value', 'Yes, all C parameters are references', 'Only if the parameter has the same name', 'Yes, if the function returns void'], 'C passes argument values. Modifying a caller object requires an appropriate pointer or another explicit access path.', 'Variable names do not create shared storage across calls.'],
    [38, 'A macro argument evaluated twice', 'macros', 'hard', 'Why is SQUARE(next_value()) risky if SQUARE(value) expands to ((value) * (value))?', ['The expansion calls next_value twice', 'The preprocessor guarantees one cached function result', 'All function calls inside macros are ignored', 'The macro automatically adds a mutex'], 'Macros perform textual substitution, so an argument used twice can repeat side effects. An ordinary function can evaluate its argument once before the call.', 'Count appearances of the substituted argument.'],
    [39, 'Structure member through a pointer', 'structs', 'easy', 'For a valid pointer item to a structure with member count, what is item->count equivalent to?', ['(*item).count', '*item.count', '&item.count', 'item[count]'], 'The arrow operator dereferences the structure pointer and then selects its member.', 'Operator precedence makes the parentheses meaningful.'],
    [40, 'Bounded buffer input', 'input-output', 'medium', 'Why is fgets(buffer, sizeof buffer, stream) useful when buffer is an actual fixed-size character array in scope?', ['It bounds input by the available array size', 'It reads arbitrarily many characters without using storage', 'It guarantees every line fits in one call', 'It automatically strips every newline and whitespace character'], 'fgets reads at most size minus one characters and terminates successful input. Long lines can require additional handling, and a newline may remain.', 'Bounding a read does not guarantee consuming a whole line.']
  ])
];
