/**
 * Presentational primitives with no business logic. Anything may import them;
 * they import nothing but types and config.
 */
export { CodeBlock } from './primitives/CodeBlock';
export { CodeEditor } from './primitives/CodeEditor';
export { PageHeader } from './primitives/PageHeader';
export { LearningModeSwitch } from './primitives/LearningModeSwitch';
export { ErrorBoundary } from './primitives/ErrorBoundary';
export { DevHint } from './primitives/DevHint';
export { ToastProvider, Toasts, useToast } from './primitives/toast';
export type { Toast, ToastTone } from './primitives/toast';
export { useFocusTrap } from './hooks/useFocusTrap';
export { useBodyScrollLock } from './hooks/useBodyScrollLock';
export { tokenize, tokenizeLine } from './code/highlight';
export { PageSkeleton, AppSplash, Bone } from './primitives/Skeleton';
export { Dropdown } from './primitives/Dropdown';
export type { DropdownOption, DropdownProps } from './primitives/Dropdown';
export { Button, ButtonLink, buttonClass } from './primitives/Button';
export type { ButtonProps, ButtonVariant, ButtonSize } from './primitives/Button';
export { Panel } from './primitives/Panel';
export { Badge } from './primitives/Badge';
export type { BadgeTone } from './primitives/Badge';
export { ProgressBar } from './primitives/ProgressBar';
export { Stat } from './primitives/Stat';
export { SectionHeader } from './primitives/SectionHeader';
export { EmptyState } from './primitives/EmptyState';
export { Switch } from './primitives/Switch';
export { Segmented } from './primitives/Segmented';
export { ProgressRing } from './primitives/ProgressRing';
export { StreakFlame } from './primitives/StreakFlame';
export type { StreakFlameState } from './primitives/StreakFlame';
export { ChoiceCards } from './primitives/ChoiceCards';
export type { ChoiceCardOption, ChoiceCardVia } from './primitives/ChoiceCards';
export { TrackChoiceList } from './primitives/TrackChoiceList';
export type { TrackChoice } from './primitives/TrackChoiceList';
export { LearningModeCards } from './primitives/LearningModeCards';
export type { LearningModeCardCopy } from './primitives/LearningModeCards';
export { StreakStrip } from './primitives/StreakStrip';
export type { StreakStripDay, StreakStripState } from './primitives/StreakStrip';
export { GoalMetCard } from './primitives/GoalMetCard';
export type { SegmentedOption } from './primitives/Segmented';
export { Card } from './primitives/Card';
export type { CardProps, CardVariant, CardPadding } from './primitives/Card';
export { GlassPanel } from './primitives/GlassPanel';
export { Modal } from './primitives/Modal';
export type { ModalProps, ModalSize } from './primitives/Modal';
export { Tabs, TabPanel } from './primitives/Tabs';
export type { TabItem } from './primitives/Tabs';
export { Tooltip } from './primitives/Tooltip';
export type { TooltipPlacement } from './primitives/Tooltip';
export { Menu, MenuItem, MenuSeparator } from './primitives/Menu';
export type { MenuTriggerProps } from './primitives/Menu';
export { StatCard } from './primitives/StatCard';
export type { StatCardTone } from './primitives/StatCard';
export { LearningCard } from './primitives/LearningCard';
export { ChallengeCard } from './primitives/ChallengeCard';
export type { ChallengeCardStatus, ChallengeCardDifficulty } from './primitives/ChallengeCard';
export { RoadmapNode } from './primitives/RoadmapNode';
export type { RoadmapNodeState } from './primitives/RoadmapNode';
export { Kbd } from './primitives/Kbd';
export { Avatar } from './primitives/Avatar';
export { Spinner } from './primitives/Spinner';
export { Section, Container } from './primitives/Layout';
// Scroll reveal, moved here from the landing page so any page can use it.
export { Reveal, useInView, CountUp } from './primitives/Reveal';
// The welcome intro's split logo layers are their own entry
// (`@/ui/brand/logoLayers`), kept out of this barrel and so out of the shell.
export { CodeConsistLogo, DevlingoLogo, CODECONSIST_LOGO_URL, DEVLINGO_LOGO_URL } from './primitives/DevlingoLogo';
export type { LogoSize, CodeConsistLogoProps, DevlingoLogoProps } from './primitives/DevlingoLogo';
